In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv


In [2]:
ds=pd.read_csv("TrainingData.csv")
ds

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0         100     100     100     100     100     100     100     100     100   
1         100     100     100     100     100     100     100     100     100   
2         100     100     100     100     100     100     100     -97     100   
3         100     100     100     100     100     100     100     100     100   
4         100     100     100     100     100     100     100     100     100   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
19932     100     100     100     100     100     100     100     100     100   
19933     100     100     100     100     100     100     100     100     100   
19934     100     100     100     100     100     100     100     100     100   
19935     100     100     100     100     100     100     100     100     100   
19936     100     100     100     100     100     100     100     100     100   

       WAP010  ...  LONGITUDE     LATITUDE  FLOOR  BUILDINGID  SPACEID  \
0         100  ... -7541.2643  4864920.778      2           1      106   
1         100  ... -7536.6212  4864934.225      2           1      106   
2         100  ... -7519.1524  4864949.532      2           1      103   
3         100  ... -7524.5704  4864934.093      2           1      102   
4         100  ... -7632.1436  4864982.217      0           0      122   
...       ...  ...        ...          ...    ...         ...      ...   
19932     100  ... -7485.4686  4864874.716      3           1        1   
19933     100  ... -7390.6206  4864836.056      1           2      140   
19934     100  ... -7516.8415  4864889.291      3           1       13   
19935     100  ... -7537.3219  4864895.776      3           1      113   
19936     100  ... -7536.1658  4864897.859      3           1      112   

       RELATIVEPOSITION  USERID  PHONEID   TIMESTAMP   New  
0                     2       2       23  1371713733   721  
1                     2       2       23  1371713691   721  
2                     2       2       23  1371714095   721  
3                     2       2       23  1371713807   721  
4                     2      11       13  1369909710     0  
...                 ...     ...      ...         ...   ...  
19932                 2      18       10  1371710683  3646  
19933                 2      18       10  1371710402    47  
19934                 2      18       10  1371710921  3646  
19935                 2      18       10  1371711049  3646  
19936                 2      18       10  1371711025  3646  

[19937 rows x 530 columns]

In [3]:
X=ds.copy()
y=X.BUILDINGID
col=["USERID","RELATIVEPOSITION","PHONEID","TIMESTAMP","FLOOR",'SPACEID','BUILDINGID']
X.drop(col, axis=1, inplace=True)
X

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0         100     100     100     100     100     100     100     100     100   
1         100     100     100     100     100     100     100     100     100   
2         100     100     100     100     100     100     100     -97     100   
3         100     100     100     100     100     100     100     100     100   
4         100     100     100     100     100     100     100     100     100   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
19932     100     100     100     100     100     100     100     100     100   
19933     100     100     100     100     100     100     100     100     100   
19934     100     100     100     100     100     100     100     100     100   
19935     100     100     100     100     100     100     100     100     100   
19936     100     100     100     100     100     100     100     100     100   

       WAP010  ...  WAP514  WAP515  WAP516  WAP517  WAP518  WAP519  WAP520  \
0         100  ...     100     100     100     100     100     100     100   
1         100  ...     100     100     100     100     100     100     100   
2         100  ...     100     100     100     100     100     100     100   
3         100  ...     100     100     100     100     100     100     100   
4         100  ...     100     100     100     100     100     100     100   
...       ...  ...     ...     ...     ...     ...     ...     ...     ...   
19932     100  ...     100     100     100     100     100     100     100   
19933     100  ...     100     100     100     100     100     100     100   
19934     100  ...     100     100     100     100     100     100     100   
19935     100  ...     100     100     100     100     100     100     100   
19936     100  ...     100     100     100     100     100     100     100   

       LONGITUDE     LATITUDE   New  
0     -7541.2643  4864920.778   721  
1     -7536.6212  4864934.225   721  
2     -7519.1524  4864949.532   721  
3     -7524.5704  4864934.093   721  
4     -7632.1436  4864982.217     0  
...          ...          ...   ...  
19932 -7485.4686  4864874.716  3646  
19933 -7390.6206  4864836.056    47  
19934 -7516.8415  4864889.291  3646  
19935 -7537.3219  4864895.776  3646  
19936 -7536.1658  4864897.859  3646  

[19937 rows x 523 columns]

In [4]:
ds['FLOOR'].value_counts()

3    5048
1    5002
2    4416
0    4369
4    1102
Name: FLOOR, dtype: int64

In [5]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X= sc.fit_transform(X)
X

array([[1.        , 1.        , 0.        , ..., 0.38429357, 0.64601411,
        0.06257594],
       [1.        , 1.        , 0.        , ..., 0.39618312, 0.69564447,
        0.06257594],
       [1.        , 1.        , 0.        , ..., 0.44091534, 0.75213975,
        0.06257594],
       ...,
       [1.        , 1.        , 0.        , ..., 0.44683285, 0.52980147,
        0.31643812],
       [1.        , 1.        , 0.        , ..., 0.39438885, 0.55373639,
        0.31643812],
       [1.        , 1.        , 0.        , ..., 0.39734926, 0.56142436,
        0.31643812]])

In [6]:
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RandomizedSearchCV

In [7]:
from sklearn.feature_selection import SelectKBest, chi2
X = SelectKBest(chi2, k=200).fit_transform(X,y)
X

array([[1.        , 1.        , 1.        , ..., 0.38429357, 0.64601411,
        0.06257594],
       [1.        , 1.        , 1.        , ..., 0.39618312, 0.69564447,
        0.06257594],
       [1.        , 0.00505051, 1.        , ..., 0.44091534, 0.75213975,
        0.06257594],
       ...,
       [1.        , 1.        , 1.        , ..., 0.44683285, 0.52980147,
        0.31643812],
       [1.        , 1.        , 1.        , ..., 0.39438885, 0.55373639,
        0.31643812],
       [1.        , 1.        , 1.        , ..., 0.39734926, 0.56142436,
        0.31643812]])

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4, random_state=None, shuffle=True)
kf.get_n_splits(X)

4

In [25]:
np.random.seed(3)
#RF
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(n_estimators=2)
rf_score  =[]
rft_score=[]
rf_pre=[]
rf_rec=[]
rf_f1=[]
lr_sen=[]
lr_roc=[]
for train_index, test_index in kf.split(X):
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test   = X[test_index], y[test_index]
    RF.fit(X_train,y_train)
    pred_rf=RF.predict(X_test)
    accur_rf=accuracy_score(y_test,pred_rf)
    pred1_rf=RF.predict(X_train)
    accur1_rf=accuracy_score(y_train,pred1_rf)
    rf_score.append(accur_rf)
    rft_score.append(accur1_rf)
    y_pred_proba = RF.predict_proba(X_test)
    prec_rf=precision_score(y_test,pred_rf,average='macro')
    rf_pre.append(prec_rf)
    rec_rf=recall_score(y_test,pred_rf,average='macro')
    rf_rec.append(rec_rf)
    f1_rf=f1_score(y_test,pred_rf,average='macro')
    rf_f1.append(f1_rf)
    rf_confusion=confusion_matrix(y_test,pred_rf)
    print(rf_confusion)
    sensitivity = rf_confusion[0,0]/(rf_confusion[0,0]+rf_confusion[0,1])
    ROC_score=roc_auc_score(y_test,y_pred_proba , average='weighted', multi_class='ovr')
    lr_sen.append(sensitivity)
    lr_roc.append(ROC_score)
print('ROC_Score : ',np.mean (lr_roc))
print('Sensitivity : ',np.mean (lr_sen))
print('Scores for RF :',rf_score)
print('Mean Test Score for RF:',np.mean(rf_score))
print('Scores for RFt :',rft_score)
print('Mean Training Score for RFt:',np.mean(rft_score))
print('Precision Scores for RF :',rf_pre)
print('Mean Precision Score for RF:',np.mean(rf_pre))
print('Recall Scores for RF :',rf_rec)
print('Mean Recall Score for RF:',np.mean(rf_rec))
print('f1 Scores for RF :',rf_f1)
print('Mean f1 Score for RF:',np.mean(rf_f1))

[[1249    0    0]
 [   2 1303    0]
 [   0    4 2427]]
[[1321    0    0]
 [   0 1326    0]
 [   0    4 2333]]
[[1309    0    0]
 [   3 1276    0]
 [   0    5 2391]]
[[1370    0    0]
 [   0 1286    0]
 [   0    0 2328]]
ROC_Score :  0.9998627013696608
Sensitivity :  1.0
Scores for RF : [0.9987963891675025, 0.9991974317817014, 0.9983948635634029, 1.0]
Mean Test Score for RF: 0.9990971711281517
Scores for RFt : [0.999665596575709, 0.9998662475757373, 0.999799371363606, 1.0]
Mean Training Score for RFt: 0.999832803878763
Precision Scores for RF : [0.9984469450708242, 0.9989974937343359, 0.9979367380032115, 1.0]
Mean Precision Score for RF: 0.9988452942020929
Recall Scores for RF : [0.998940673180024, 0.9994294679788903, 0.998522535387143, 1.0]
Mean Recall Score for RF: 0.9992231691365143
f1 Scores for RF : [0.9986931751796977, 0.9992124816181214, 0.9982286343980387, 1.0]
Mean f1 Score for RF: 0.9990335727989644


In [31]:
np.random.seed(3)
#KNN
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
RF=KNeighborsClassifier()
rf_score  =[]
rft_score=[]
rf_pre=[]
rf_rec=[]
rf_f1=[]
lr_sen=[]
lr_roc=[]
for train_index, test_index in kf.split(X):
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test   = X[test_index], y[test_index]
    RF.fit(X_train,y_train)
    pred_rf=RF.predict(X_test)
    accur_rf=accuracy_score(y_test,pred_rf)
    pred1_rf=RF.predict(X_train)
    accur1_rf=accuracy_score(y_train,pred1_rf)
    rf_score.append(accur_rf)
    rft_score.append(accur1_rf)
    y_pred_proba = RF.predict_proba(X_test)
    prec_rf=precision_score(y_test,pred_rf,average='macro')
    rf_pre.append(prec_rf)
    rec_rf=recall_score(y_test,pred_rf,average='macro')
    rf_rec.append(rec_rf)
    f1_rf=f1_score(y_test,pred_rf,average='macro')
    rf_f1.append(f1_rf)
    rf_confusion=confusion_matrix(y_test,pred_rf)
    print(rf_confusion)
    sensitivity = rf_confusion[0,0]/(rf_confusion[0,0]+rf_confusion[0,1])
    ROC_score=roc_auc_score(y_test,y_pred_proba , average='weighted', multi_class='ovr')
    lr_sen.append(sensitivity)
    lr_roc.append(ROC_score)
print('ROC_Score : ',np.mean (lr_roc))
print('Sensitivity : ',np.mean (lr_sen))
print('Scores for RF :',rf_score)
print('Mean Test Score for RF:',np.mean(rf_score))
print('Scores for RFt :',rft_score)
print('Mean Training Score for RFt:',np.mean(rft_score))
print('Precision Scores for RF :',rf_pre)
print('Mean Precision Score for RF:',np.mean(rf_pre))
print('Recall Scores for RF :',rf_rec)
print('Mean Recall Score for RF:',np.mean(rf_rec))
print('f1 Scores for RF :',rf_f1)
print('Mean f1 Score for RF:',np.mean(rf_f1))

[[1249    0    0]
 [   0 1304    1]
 [   0    3 2428]]
[[1321    0    0]
 [   0 1325    1]
 [   0    0 2337]]
[[1308    1    0]
 [   0 1277    2]
 [   0    0 2396]]
[[1368    2    0]
 [   0 1285    1]
 [   0    3 2325]]
ROC_Score :  0.9998490363026873
Sensitivity :  0.9994440510112472
Scores for RF : [0.999197592778335, 0.9997993579454254, 0.9993980738362761, 0.9987961476725522]
Mean Test Score for RF: 0.9992977930581473
Scores for RFt : [0.9995987158908507, 0.9995318665150806, 0.9996656189393432, 0.9997324951514747]
Mean Training Score for RFt: 0.9996321741241874
Precision Scores for RF : [0.9990976583741324, 0.9998574280011406, 0.9994611663431924, 0.9985647027979407]
Mean Precision Score for RF: 0.9992452388791015
Recall Scores for RF : [0.9993332188058354, 0.9997486173956762, 0.9992241121340143, 0.9988246270716384]
Mean Recall Score for RF: 0.9992826438517911
f1 Scores for RF : [0.9992151870547877, 0.9998029600372779, 0.9993424816727116, 0.9986936238478953]
Mean f1 Score for RF: 0.9

In [32]:
np.random.seed(3)
#CatBoost
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
RF=CatBoostClassifier(n_estimators=7,reg_lambda=0.1)
rf_score  =[]
rft_score=[]
rf_pre=[]
rf_rec=[]
rf_f1=[]
lr_sen=[]
lr_roc=[]
for train_index, test_index in kf.split(X):
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test   = X[test_index], y[test_index]
    RF.fit(X_train,y_train)
    pred_rf=RF.predict(X_test)
    accur_rf=accuracy_score(y_test,pred_rf)
    pred1_rf=RF.predict(X_train)
    accur1_rf=accuracy_score(y_train,pred1_rf)
    rf_score.append(accur_rf)
    rft_score.append(accur1_rf)
    y_pred_proba = RF.predict_proba(X_test)
    prec_rf=precision_score(y_test,pred_rf,average='macro')
    rf_pre.append(prec_rf)
    rec_rf=recall_score(y_test,pred_rf,average='macro')
    rf_rec.append(rec_rf)
    f1_rf=f1_score(y_test,pred_rf,average='macro')
    rf_f1.append(f1_rf)
    rf_confusion=confusion_matrix(y_test,pred_rf)
    print(rf_confusion)
    sensitivity = rf_confusion[0,0]/(rf_confusion[0,0]+rf_confusion[0,1])
    ROC_score=roc_auc_score(y_test,y_pred_proba , average='weighted', multi_class='ovr')
    lr_sen.append(sensitivity)
    lr_roc.append(ROC_score)
print('ROC_Score : ',np.mean (lr_roc))
print('Sensitivity : ',np.mean (lr_sen))
print('Scores for RF :',rf_score)
print('Mean Test Score for RF:',np.mean(rf_score))
print('Scores for RFt :',rft_score)
print('Mean Training Score for RFt:',np.mean(rft_score))
print('Precision Scores for RF :',rf_pre)
print('Mean Precision Score for RF:',np.mean(rf_pre))
print('Recall Scores for RF :',rf_rec)
print('Mean Recall Score for RF:',np.mean(rf_rec))
print('f1 Scores for RF :',rf_f1)
print('Mean f1 Score for RF:',np.mean(rf_f1))

0:	learn: 1.0409908	total: 323ms	remaining: 1.94s
1:	learn: 0.9879956	total: 381ms	remaining: 951ms
2:	learn: 0.9382256	total: 465ms	remaining: 620ms
3:	learn: 0.8940772	total: 519ms	remaining: 389ms
4:	learn: 0.8522130	total: 590ms	remaining: 236ms
5:	learn: 0.8141284	total: 641ms	remaining: 107ms
6:	learn: 0.7776542	total: 695ms	remaining: 0us
[[1249    0    0]
 [   0 1273   32]
 [   0    2 2429]]
0:	learn: 1.0416015	total: 64.3ms	remaining: 386ms
1:	learn: 0.9874412	total: 125ms	remaining: 313ms
2:	learn: 0.9378371	total: 186ms	remaining: 248ms
3:	learn: 0.8930689	total: 253ms	remaining: 190ms
4:	learn: 0.8513938	total: 316ms	remaining: 127ms
5:	learn: 0.8118291	total: 379ms	remaining: 63.2ms
6:	learn: 0.7763808	total: 437ms	remaining: 0us
[[1321    0    0]
 [   0 1307   19]
 [   0    0 2337]]
0:	learn: 1.0409866	total: 63.8ms	remaining: 383ms
1:	learn: 0.9869257	total: 138ms	remaining: 345ms
2:	learn: 0.9375749	total: 200ms	remaining: 267ms
3:	learn: 0.8928152	total: 309ms	remainin

In [29]:
np.random.seed(42)
#MLP
from sklearn.neural_network import MLPClassifier
gb_score  =[]
gbt_score=[]
gb_pre=[]
gb_rec=[]
gb_f1=[]
lr_sen=[]
lr_roc=[]
for train_index, test_index in kf.split(X,y):
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test   = X[test_index], y[test_index]
    
    parameters = {'hidden_layer_sizes': (10,100,300,500,800),'alpha': (0.0001,0.3,0.001,0.1,0.5,1,3,5),'random_state': (0,1),'tol': (0.0001,0.01
                                                                                                                                     ,0.001,.1,1,10,50)}
    DT_grid  = RandomizedSearchCV( MLPClassifier(), param_distributions = parameters, cv = 5, verbose = True,scoring='accuracy')
    result=DT_grid.fit(X_train,y_train)
    
    gb = result.best_estimator_
    pred_mlp = gb.predict(X_test)
    y_pred_proba = gb.predict_proba(X_test) 
    pred1_gb=gb.predict(X_train)
    accur_gb=accuracy_score(y_test,pred_mlp)
    accur1_gb=accuracy_score(y_train,pred1_gb)
    gb_score.append(accur_gb)
    gbt_score.append(accur1_gb)
    prec_gb=precision_score(y_test,pred_mlp,average='weighted')
    gb_pre.append(prec_gb)
    rec_gb=recall_score(y_test,pred_mlp,average='weighted')
    gb_rec.append(rec_gb)
    f1_gb=f1_score(y_test,pred_mlp,average='weighted')
    gb_f1.append(f1_gb)
    gb_confusion=confusion_matrix(y_test,pred_mlp)
    print(gb_confusion)
    sensitivity = gb_confusion[0,0]/(gb_confusion[0,0]+gb_confusion[0,1])
    ROC_score=roc_auc_score(y_test,y_pred_proba , average='weighted', multi_class='ovr')
    lr_sen.append(sensitivity)
    lr_roc.append(ROC_score)
    print(gb)
print('ROC_Score : ',np.mean (lr_roc))
print('Sensitivity : ',np.mean (lr_sen))
print('Scores for gb :',gb_score)
print('Mean Test Score for gb:',np.mean(gb_score))
print('Scores for gbt :',gbt_score)
print('Mean Training Score for gbt:',np.mean(gbt_score))
print('Precision Scores for gb :',gb_pre)
print('Mean Precision Score for gb:',np.mean(gb_pre))
print('Recall Scores for gb :',gb_rec)
print('Mean Recall Score for gb:',np.mean(gb_rec))
print('f1 Scores for gb :',gb_f1)
print('Mean f1 Score for gb:',np.mean(gb_f1))

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[[1328    5    0]
 [   0 1263    0]
 [   0   11 2378]]
MLPClassifier(alpha=0.5, hidden_layer_sizes=800, random_state=1, tol=10)
Fitting 5 folds for each of 10 candidates, totalling 50 fits
[[1307    0    0]
 [   0 1346    0]
 [   0   12 2319]]
MLPClassifier(alpha=3, hidden_layer_sizes=500, random_state=0, tol=0.001)
Fitting 5 folds for each of 10 candidates, totalling 50 fits
[[1324    1    0]
 [   0 1274    0]
 [   0   12 2373]]
MLPClassifier(alpha=1, hidden_layer_sizes=500, random_state=1, tol=1)
Fitting 5 folds for each of 10 candidates, totalling 50 fits
[[1284    0    0]
 [   0 1313    0]
 [   0    1 2386]]
MLPClassifier(alpha=0.1, hidden_layer_sizes=800, random_state=1, tol=0.001)
ROC_Score :  0.999999499415401
Sensitivity :  0.9988735863211086
Scores for gb : [0.99679037111334, 0.9975922953451043, 0.9973916532905297, 0.9997993579454254]
Mean Test Score for gb: 0.9978934194235998
Scores for gbt : [0.997792937399679, 0.9

In [30]:
np.random.seed(3)
#xgbrf
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
knn=XGBRFClassifier(reg_lambda=0.5)
rf_score  =[]
rft_score=[]
rf_pre=[]
rf_rec=[]
rf_f1=[]
lr_sen=[]
lr_roc=[]
for train_index, test_index in kf.split(X):
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test   = X[test_index], y[test_index]
    RF.fit(X_train,y_train)
    pred_rf=RF.predict(X_test)
    accur_rf=accuracy_score(y_test,pred_rf)
    pred1_rf=RF.predict(X_train)
    accur1_rf=accuracy_score(y_train,pred1_rf)
    rf_score.append(accur_rf)
    rft_score.append(accur1_rf)
    y_pred_proba = RF.predict_proba(X_test)
    prec_rf=precision_score(y_test,pred_rf,average='macro')
    rf_pre.append(prec_rf)
    rec_rf=recall_score(y_test,pred_rf,average='macro')
    rf_rec.append(rec_rf)
    f1_rf=f1_score(y_test,pred_rf,average='macro')
    rf_f1.append(f1_rf)
    rf_confusion=confusion_matrix(y_test,pred_rf)
    print(rf_confusion)
    sensitivity = rf_confusion[0,0]/(rf_confusion[0,0]+rf_confusion[0,1])
    ROC_score=roc_auc_score(y_test,y_pred_proba , average='weighted', multi_class='ovr')
    lr_sen.append(sensitivity)
    lr_roc.append(ROC_score)
print('ROC_Score : ',np.mean (lr_roc))
print('Sensitivity : ',np.mean (lr_sen))
print('Scores for RF :',rf_score)
print('Mean Test Score for RF:',np.mean(rf_score))
print('Scores for RFt :',rft_score)
print('Mean Training Score for RFt:',np.mean(rft_score))
print('Precision Scores for RF :',rf_pre)
print('Mean Precision Score for RF:',np.mean(rf_pre))
print('Recall Scores for RF :',rf_rec)
print('Mean Recall Score for RF:',np.mean(rf_rec))
print('f1 Scores for RF :',rf_f1)
print('Mean f1 Score for RF:',np.mean(rf_f1))

H:\Anaconda\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:11:15] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[1249    0    0]
 [   0 1305    0]
 [   0    0 2431]]


H:\Anaconda\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:11:23] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[1321    0    0]
 [   0 1326    0]
 [   0    0 2337]]


H:\Anaconda\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:11:31] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[1309    0    0]
 [   0 1279    0]
 [   0    0 2396]]


H:\Anaconda\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:11:38] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[1370    0    0]
 [   0 1286    0]
 [   0    0 2328]]
ROC_Score :  1.0
Sensitivity :  1.0
Scores for RF : [1.0, 1.0, 1.0, 1.0]
Mean Test Score for RF: 1.0
Scores for RFt : [1.0, 1.0, 1.0, 1.0]
Mean Training Score for RFt: 1.0
Precision Scores for RF : [1.0, 1.0, 1.0, 1.0]
Mean Precision Score for RF: 1.0
Recall Scores for RF : [1.0, 1.0, 1.0, 1.0]
Mean Recall Score for RF: 1.0
f1 Scores for RF : [1.0, 1.0, 1.0, 1.0]
Mean f1 Score for RF: 1.0
